name: todo_app
description: A complete To-Do app with due dates, categories, filtering, and themes.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # For date formatting and localization
  intl: ^0.19.0

  # For selecting dates
  flutter_localizations:
    sdk: flutter

  # For generating unique IDs
  uuid: ^4.3.3 # Ensure this is present from previous updates

  # NEW: For SQLite database storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
